name: "Pull Request Labeler"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - id: label
        uses: actions/labeler@v4
        with:
          sync-labels: true
          repo-token: ${{ secrets.PAT }}
