name: release

on:
  # Rerun the release workflow on change to this repo
  push:
    branches: [ "dev", "main" ]

jobs:

  # Build the patterns site
  dispatch-release:
    runs-on: ubuntu-latest
    steps:

      - name: Dispatch release request
        run: |
          curl -X POST https://api.github.com/repos/Project-Gretchen/infrastructure/dispatches \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"event_type": "Pattern content update: ${{ github.event.head_commit.message }}", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
