name: Lint and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # First ensure that the contents are valid by running the linter.
  lint-data:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run-script lint

  # Dispatch a release request to the central infrastructure repo
  dispatch-release:
    needs:
      - lint-data
    runs-on: ubuntu-latest
    steps:

      - name: Dispatch release request
        run: |
          curl -X POST https://api.github.com/repos/Project-Gretchen/infrastructure/dispatches \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"event_type": "Pattern content update: ${{ github.event.head_commit.message }}", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
